### ISSUE TITLE
Support x86 and arm64 

### ISSUE THREAD

**Issue by amaitland** [cefsharp/Puppeteer#5]
![Screenshot_272](https://user-images.githubusercontent.com/5983350/148169582-e4816b31-40cb-436e-a5dd-6f40ff447d14.png)

Error code
```
There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "CefSharp.Puppeteer, Version=1.0.22.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138, processorArchitecture=AMD64", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

_Originally posted by @radiaku in https://github.com/cefsharp/Puppeteer/discussions/4#discussioncomment-1910151_

**Comment by amaitland** [comment]
@radiaku You can try out commit https://github.com/cefsharp/Puppeteer/commit/8618ed5735f44df5d872d3f0cfdf48b3f5f98b68 if you are interested.

**Comment by radiaku** [comment]
> @radiaku You can try out commit [8618ed5](https://github.com/cefsharp/Puppeteer/commit/8618ed5735f44df5d872d3f0cfdf48b3f5f98b68) if you are interested.

Tried it and build manually, I get this one working. There is some warning notice but nevertheless its working.  Thanks for your help @amaitland 

![Screenshot_273](https://user-images.githubusercontent.com/5983350/148196906-dcfcad2d-4b4f-452d-a19b-3377569625f2.png)

**Comment by amaitland** [comment]
> There is some warning notice but nevertheless its working

There is no `x86` target in the solution, there should only be `AnyCPU` did you add `x86` yourself? You should target `AnyCPU`.

**Comment by amaitland** [comment]
Version `1.0.24` should appear on `Nuget.org` shortly which should target `AnyCPU` rather than `x64`.

**Comment by radiaku** [comment]
> > There is some warning notice but nevertheless its working
> 
> There is no `x86` target in the solution, there should only be `AnyCPU` did you add `x86` yourself? You should target `AnyCPU`.

I see.. Thanks for the info, I would use this plugin for next project. Its much easier than use socket. 

Right now , I still need use socket, cause I need use Puppeteer-sharp-extra not pupetteersharp. For google login (OAUTH2) purpose, its need stealth plugin.
But thanks for the improvement. 

Cheers
